### ISSUE TITLE
Loop over sample properties in matflow

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#16]
Original scripts looped over values of friction, conductance, and power.
I've not been able to figure out how `increments` works in matflow yet.

**Comment by gcapes** [comment]
`increments` are not a matflow thing, they're a `damask-parse` thing. `sequences` is what we need here:
```
- schema: s1
  inputs:
    p1: 101
  sequences:
    - path: inputs.p2
      values: 
        - 201
        - 202
        - 203 
```

**Comment by gcapes** [comment]
I can do a simple loop like the one above, but we want a nested loop over two sets of values, and I haven't figured that out.

**Comment by gcapes** [comment]
This is done using a `nesting_order` key at the level of the sequence item. Solved this one digging through your workshop material @aplowman 👍

**Comment by gcapes** [comment]
Hi @aplowman, 
I've got an idea of how to iterate over values, but this workflow generates a new input file for each iteration. How do I reference that as an input to the task?

So I had this for one set of values
```
tasks:
- schema: run_abaqus
  inputs:
    friction: 0.01
    conductance_value: 0
    conductance_file: "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
      /Abaqus_5_min_heatup/800nocondC_heatup22.odb"
    power: 0
    inp_file: /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/800C_1s-1_setup.inp
```
and then I would need something like this instead
```
tasks:
- schema: run_abaqus
  inputs:
  # there's only one power value currently in the code so we can leave that as it was
    power: 0
  sequences:
  - path: inputs.friction
    values:
    - 0.01
    - 0.08
    - 0.15
    - 0.22
    - 0.29
    - 0.36
    - 0.43
    - 0.5
    - 0.57
    - 0.64
    - 0.71
    - 0.78
    - 0.85
    - 0.92
    - 0.99
  - path: inputs.conductance_value
    - 0
    - 100
    - 200
  - path: inputs.conductance_file
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/800nocondC_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80010C_heatup22.odb"
    - "/mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow\
       /Abaqus_5_min_heatup/80020C_heatup22.odb"
  - path: inputs.inp_file
    values:
   # first value
    - /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/800C_1s-1_setup.inp
    # subsequent files generated by the task, and labelled `new_inp_file` under the `command_files` - can I use that somehow?

```
Workflow file is here for reference: https://github.com/RoryAtBar/Abaqus_bayesian_matflow/blob/main/workflow.yaml

**Comment by aplowman** [comment]
Is `inp_file` the "base" input file, which gets copied and then modified by the task? If so, you should only need one value for `inp_file`, shouldn't you? A new input file will be generated for each element, where the element multiplicity comes from the multiple values of the sequenced parameters. I may be misunderstanding.

**Comment by gcapes** [comment]
Yes, `inp_file` get modified and then saved by the task. I'm just asking how to tell matflow to use the modified file for each item in the sequence, because I've defined it with a full path in the workflow file, and I don't want to use the unmodified file for each iteration.

**Comment by gcapes** [comment]
Ok so it works as you expected @aplowman. 
Something I hadn't considered is that I guess the code is modifying (a copy of) the original `inp_file` on each iteration, rather than the `inp_file` from the previous iteration?

I think the one thing remaining for this part of the analysis is to combine the results files, which are currently saved as one json file per iteration. How would you recommend approaching that?

**Comment by aplowman** [comment]
Yeah, just to clarify: there is no dependence between different elements of the same task. When you use sequences, you are generating completely independent parametrisations. (MatFlow has a separate concept of loops and iterations; these are reserved for the scenarios where you do want dependency between different iterations).

To combine elements together we can use element groups. Here is a simple example workflow that uses a group, try it out and see if you can understand what's going on! We have two elements in the first task, but the elements are grouped together into one element in the second task. So when the input parameters are passed in to the second task, multiple values are passed. As a simple demonstration, here we are just summing those values together to get the output `p3` in the second task. But this could equally be a script where one/all of the input parameters in the script are lists instead of single values.

```yaml
template_components:
  task_schemas:
    - objective: s1
      inputs:
        - parameter: p1
      outputs:
        - parameter: p2
      actions:
        - commands:
            - command: echo $(( <<parameter:p1>> + 1 ))
              stdout: <<int(parameter:p2)>>
    - objective: s2
      inputs:
        - parameter: p2
          group: my_group
      outputs:
        - parameter: p3          
      actions:
        - commands:
            - command: echo $(( <<sum(parameter:p2)>> ))
              stdout: <<parameter:p3>>
tasks:
  - schema: s1
    sequences:
      - path: inputs.p1
        values: [1, 2]
    groups:
      - name: my_group
  - schema: s2
```

[Edited to correct misplaced bracket.]

**Comment by gcapes** [comment]
Thanks Adam.
I think I can follow what it's supposed to do, but I don't get any (std)output (that I can find) anywhere in my workflow directory...
I'm using matflow `MatFlow, version 0.3.0a123` in case that makes any difference to the format of the workflow above.

**Comment by aplowman** [comment]
In this case, there is no standard output because it is captured by MatFlow as the value for the output parameters. If you want to see the values printed to the jobscript's `stdout`, then you could add another command that is not captured, like this:

```yaml
template_components:
  task_schemas:
    - objective: s1
      inputs:
        - parameter: p1
      outputs:
        - parameter: p2
      actions:
        - commands:
            - command: echo $(( <<parameter:p1>> + 1 ))
            - command: echo $(( <<parameter:p1>> + 1 ))
              stdout: <<int(parameter:p2)>>
    - objective: s2
      inputs:
        - parameter: p2
          group: my_group
      outputs:
        - parameter: p3          
      actions:
        - commands:
            - command: echo $(( <<sum(parameter:p2)>> ))
            - command: echo $(( <<sum(parameter:p2)>> ))
              stdout: <<parameter:p3>>
tasks:
  - schema: s1
    sequences:
      - path: inputs.p1
        values: [1, 2]
    groups:
      - name: my_group
  - schema: s2
```

(note: I have corrected a misplaced bracket in the original template: `command: echo $(( <<sum(parameter:p2>>) ))` should have been `command: echo $(( <<sum(parameter:p2)>> ))`

**Comment by gcapes** [comment]
Cheers - I've got the output printed now.

I'm trying to understand this further in order to be able to expand upon it for Rory's workflow...
1. `p3` doesn't look to be defined anywhere, yet is returned (to stdout but captured by matflow?) as the sum of `p2` values from the group. Is that done implicitly using the `stdout` key?
2.  If I just print them using 
     ```
      actions:
        - commands:
            - command: echo <<parameter:p2>>
            - command: echo $(( <<sum(parameter:p2)>> ))
              stdout: <<parameter:p3>>
     ```

    I can see that the `p2` values arrive combined as a list as the input to the task `s2`, but I'm not sure whether I can use this approach for multiple parameters? The group looks to apply to a task rather than a particular parameter(?) For the specific example I'm working on I don't actually need to combine multiple parameters because each `p2` equivalent in the group is a dictionary of 3 lists, so the input would come as a list of dictionaries of lists which I can then reshuffle in a python script to return a dict of lists.

**Comment by aplowman** [comment]
> 1. `p3` doesn't look to be defined anywhere, yet is returned (to stdout but captured by matflow?) as the sum of `p2` values from the group. Is that done implicitly using the `stdout` key?

Yes, the command attribute: `stdout: <<parameter:p3>>` means map the standard output from the command (in this case, `echo $(( <<sum(parameter:p2)>> ))`) to the output parameter `p3`.

> 2. If I just print them using
>    ```
>     actions:
>       - commands:
>           - command: echo <<parameter:p2>>
>           - command: echo $(( <<sum(parameter:p2)>> ))
>             stdout: <<parameter:p3>>
>    ```
>      
>    I can see that the `p2` values arrive combined as a list as the input to the task `s2`, but I'm not sure whether I can use this approach for multiple parameters? The group looks to apply to a task rather than a particular parameter(?) For the specific example I'm working on I don't actually need to combine multiple parameters because each `p2` equivalent in the group is a dictionary of 3 lists, so the input would come as a list of dictionaries of lists which I can then reshuffle in a python script to return a dict of lists.

The first task as a whole has a group applied to it:
```yaml
  - schema: s1
    sequences:
      - path: inputs.p1
        values: [1, 2]
    groups:
      - name: my_group
```
This is just a label which may or may not be used by individual schema inputs in downstream tasks. So in the task schema definition for the downstream task, for any input parameters that come from the upstream task with the group defined, we can choose to use the group rather than individual elements:

```yaml
    - objective: s2
      inputs:
        - parameter: p2
          group: my_group
      ...
```
In this case, we are only using the group for the parameter `p2` (and that is the only output available from that task). But in the general case, you can choose which inputs should use the grouped elements.
