### ISSUE TITLE
User-test matflow workflow

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#18]
Hi @RoryAtBar 
I've now finished putting your first script into matflow (#16) - could you take a look and see if things work for you? You'll need to change the paths in the `workflow.yaml` file.

Thanks!

**Comment by RoryAtBar** [comment]
Do I need to change anything else in the yaml file? e.g. under the following:
```
template_components:
  environments:
  - name: abaqus_env
    setup: |
      source /mnt/iusers01/support/mbexegc2/scratch/Abaqus_bayesian_matflow/.venv/bin/activate
      module load apps/binapps/abaqus/2022
```
Do I need the environments name to match the conda environment I am using, or do I simply change the source accordingly?

Also for this section:
```
 executables:
    - label: python_script
      instances:
      - command: python <<script_name>> <<args>>
        num_cores: 1
        parallel_mode: null
```
Do I need to change `<<script_name>>` and `<<args>>`?
