### ISSUE TITLE
Make matflow task schema for `sub_script_check`

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#8]
I'm looking to make a task schema for this part of the existing script:
```
subprocess.run(['abq2022','job=sub_script_check', 'input='+original_inp_file, 'interactive'])
```
Have asked Adam for help with this. It would probably look a bit like this, but I'm not sure of the details.
```
      commands:
        - command: <<executable:damask_grid>> --load load.yaml --geom geom.vti
          stdout: stdout.log
          stderr: stderr.log
```

**Comment by aplowman** [comment]
I think this should be part of the same task schema. Generating the input file (which I think you've done already) can be an input file generator of this task schema. Something like:

```yaml
template_components:
  environments:
    - name: abaqus_env
      executables:
        - label: python_script
          instances:
            - command: python <<script_name>> <<args>>
              num_cores: 1
              parallel_mode: null
        - label: abaqus
          instances:
            - command: abq2022
              num_cores: 1
              parallel_mode: null
  command_files:
    - label: new_inp_file
      name:
        name: new.inp              
  task_schemas:
    - objective: run_abaqus
      inputs:
        - parameter: ...
        - ...
      outputs: 
        - parameter: ... 
        - ...
      actions:
        - environments:
            - scope:
                type: any
              environment: abaqus_env
          input_file_generators:
            - input_file: new_inp_file
              from_inputs: [...] # list of subset of input names required to generate the input file
              script: <<script:/path/to/generate_input_file.py>>
          commands:
            - command: <<executable:abaqus>> job=sub_script_check input=<<file:new_inp_file>> interactive

```
